-- Phase 4 hosted development-project security check. Every synthetic row rolls back.
begin;
set local plpgsql.check_asserts = on;
set constraints all immediate;
do $$
declare
  owner_a uuid:=gen_random_uuid(); owner_b uuid:=gen_random_uuid();
  day_value date:=(now() at time zone 'Asia/Kolkata')::date;
  category_a uuid; session_a uuid; timer_a uuid; saved jsonb; table_name text; seen integer; blocked boolean;
begin
  insert into auth.users(id,raw_user_meta_data) values(owner_a,'{"display_name":"Career fixture A"}'),(owner_b,'{"display_name":"Career fixture B"}');
  foreach table_name in array array['study_categories','study_sessions','focus_timers'] loop
    assert (select relrowsecurity from pg_class where oid=('public.'||table_name)::regclass), 'RLS disabled: '||table_name;
    assert has_table_privilege('authenticated','public.'||table_name,'select'), 'Authenticated read denied: '||table_name;
    assert not has_table_privilege('authenticated','public.'||table_name,'insert'), 'Direct insert permitted: '||table_name;
    assert not has_table_privilege('authenticated','public.'||table_name,'update'), 'Direct update permitted: '||table_name;
    assert not has_table_privilege('authenticated','public.'||table_name,'delete'), 'Direct delete permitted: '||table_name;
    execute 'set local role anon';
    blocked:=false;
    begin execute format('select count(*) from public.%I',table_name) into seen;
    exception when insufficient_privilege then blocked:=true; end;
    assert blocked, 'Anonymous read permitted: '||table_name;
    execute 'reset role';
    execute 'set local role authenticated';
    perform set_config('request.jwt.claim.sub',owner_a::text,true);
    execute format('select count(*) from public.%I where user_id=$1',table_name) into seen using owner_b;
    assert seen=0, 'Cross-owner read permitted: '||table_name;
    execute 'reset role';
  end loop;
  execute 'set local role authenticated';
  perform set_config('request.jwt.claim.sub',owner_a::text,true);
  perform public.setup_career('{"dailyMinutes":150,"weeklyMinutes":720}'::jsonb);
  perform public.setup_career('{"dailyMinutes":150,"weeklyMinutes":720}'::jsonb);
  assert (select count(*) from public.metric_definitions where user_id=owner_a and starter_key='study-duration')=1, 'Career setup duplicated metric';
  assert (select count(*) from public.study_sessions where user_id=owner_a)=0, 'Career setup fabricated time';
  saved:=public.save_study_category('{"name":"Systems","position":0}'::jsonb);
  category_a:=(saved->>'id')::uuid;
  saved:=public.save_study_session(jsonb_build_object('categoryId',category_a,'challengeId',null,'date',day_value,'durationSeconds',5400,'startAt',null,'endAt',null,'topic','Fixture','notes',''));
  session_a:=(saved->>'id')::uuid;
  saved:=public.start_focus_timer(jsonb_build_object('categoryId',category_a,'topic','Fixture timer'));
  timer_a:=(saved->>'id')::uuid;
  blocked:=false;
  begin perform public.start_focus_timer(jsonb_build_object('categoryId',category_a));
  exception when unique_violation then blocked:=true; end;
  assert blocked, 'Second active timer permitted';
  execute 'reset role';
  execute 'set local role authenticated';
  perform set_config('request.jwt.claim.sub',owner_b::text,true);
  assert (select count(*) from public.study_sessions where id=session_a)=0, 'Cross-owner session read permitted';
  blocked:=false;
  begin perform public.start_focus_timer(jsonb_build_object('categoryId',category_a));
  exception when insufficient_privilege then blocked:=true; end;
  assert blocked, 'Cross-owner category accepted';
  blocked:=false;
  begin perform public.control_focus_timer(timer_a,'discard',1);
  exception when insufficient_privilege then blocked:=true; end;
  assert blocked, 'Cross-owner timer mutation accepted';
  execute 'reset role';
end;
$$;
rollback;
select 'Phase 4 career security checks passed; all fixtures rolled back' as result;
