/** Domain contracts for the migrated Phase 2 tracking schema. */
export type BusinessDate = string;
export type Period = "daily" | "weekly" | "monthly";
export type HabitFrequency = "DAILY" | "WEEKDAYS" | "SPECIFIC_DAYS" | "TIMES_PER_WEEK" | "TIMES_PER_MONTH" | "CUSTOM";
export type MetricSource = "manual" | "study" | "sleep";
export type FrequencySource = "metric_threshold" | "workouts" | "study_sessions";
export type OwnedRecord = { id: string; user_id: string; created_at: string; updated_at: string };
export type ActiveRecord = { active_from: BusinessDate; active_until: BusinessDate | null; archived_on: BusinessDate | null; archived_at: string | null };
export type EffectiveRecord = { effective_from: BusinessDate; effective_until: BusinessDate | null; timezone: string; week_starts_on: number };
export type Challenge = OwnedRecord & { title: string; description: string; start_date: BusinessDate; end_date: BusinessDate; status: "upcoming" | "active" | "completed" | "archived"; color: string | null; icon: string | null; starter_key: string | null };
export type Habit = OwnedRecord & ActiveRecord & { name: string; description: string; icon: string | null; category_id: string | null; time_of_day: "morning" | "afternoon" | "evening" | "anytime"; is_private: boolean; dosage_amount: number | null; dosage_unit: string | null; starter_key: string | null };
export type HabitSchedule = OwnedRecord & EffectiveRecord & { habit_id: string; frequency: HabitFrequency; required_count: number; weekdays: number[]; interval_days: number | null; anchor_date: BusinessDate | null };
export type HabitLog = OwnedRecord & { habit_id: string; business_date: BusinessDate; timezone: string; status: "completed" | "missed" | "skipped"; completion_count: number; notes: string; revision: number };
export type MetricDefinition = OwnedRecord & ActiveRecord & { name: string; description: string; category_id: string | null; unit: string; source: MetricSource; aggregation: "sum" | "latest" | "average"; is_private: boolean; source_available_from: BusinessDate | null; starter_key: string | null };
export type MetricTarget = OwnedRecord & EffectiveRecord & { metric_id: string; period: Period; direction: "minimum" | "maximum"; target: number };
export type MetricLog = OwnedRecord & { metric_id: string; business_date: BusinessDate; timezone: string; value: number; notes: string; revision: number };
export type FrequencyTarget = OwnedRecord & ActiveRecord & { name: string; description: string; category_id: string | null; source: FrequencySource; metric_id: string | null; count_mode: "sessions" | "distinct_days"; is_private: boolean; source_available_from: BusinessDate | null; starter_key: string | null };
export type FrequencyRule = OwnedRecord & EffectiveRecord & { frequency_target_id: string; period: "weekly" | "monthly"; quota: number; threshold: number | null };
export type ScoreCategory = OwnedRecord & { name: string; position: number; archived_at: string | null; starter_key: string | null };
export type ScorePolicy = OwnedRecord & EffectiveRecord & { name: string; period: Period; version: number };
export type ScoreCategoryWeight = OwnedRecord & { policy_id: string; score_category_id: string; weight: number };
export type ScoreItem = OwnedRecord & { policy_id: string; score_category_id: string; weight: number; habit_id: string | null; metric_id: string | null; frequency_target_id: string | null };
export type ChallengeHabit = OwnedRecord & { challenge_id: string; habit_id: string };
export type ChallengeMetric = OwnedRecord & { challenge_id: string; metric_id: string };
export type ChallengeTarget = OwnedRecord & { challenge_id: string; frequency_target_id: string };
export type SleepLog = OwnedRecord & { business_date: BusinessDate; timezone: string; sleep_start_at: string | null; wake_at: string | null; duration_seconds: number; quality: number | null; notes: string; revision: number };
export type Exercise = OwnedRecord & { name: string; muscle_group: string; archived_at: string | null };
export type Workout = OwnedRecord & { business_date: BusinessDate; timezone: string; name: string; duration_seconds: number | null; notes: string; status: "draft" | "completed"; challenge_id: string | null; revision: number };
export type WorkoutExercise = OwnedRecord & { workout_id: string; exercise_id: string; position: number; notes: string };
export type WorkoutSet = OwnedRecord & { workout_exercise_id: string; set_number: number; weight_kg: number; reps: number; rpe: number | null };
export type TrackingCategory = OwnedRecord & { name: string; life_area_id: string | null; position: number; archived_at: string | null };
export type TrackingLifeArea = OwnedRecord & { name: string; icon: string | null; color: string | null; position: number; archived_at: string | null };
export type TrackingSnapshot = {
  challenges: Challenge[]; challengeHabits: ChallengeHabit[]; challengeMetrics: ChallengeMetric[]; challengeTargets: ChallengeTarget[];
  habits: Habit[]; schedules: HabitSchedule[]; habitLogs: HabitLog[];
  metrics: MetricDefinition[]; metricTargets: MetricTarget[]; metricLogs: MetricLog[];
  frequencyTargets: FrequencyTarget[]; frequencyRules: FrequencyRule[];
  scoreCategories: ScoreCategory[]; scorePolicies: ScorePolicy[]; scoreWeights: ScoreCategoryWeight[]; scoreItems: ScoreItem[];
  categories: TrackingCategory[]; lifeAreas: TrackingLifeArea[];
  sleepLogs: SleepLog[]; exercises: Exercise[]; workouts: Workout[]; workoutExercises: WorkoutExercise[]; workoutSets: WorkoutSet[];
  timezone: string; weekStartsOn: number; today: BusinessDate; selectedChallengeId: string | null;
  onboardingComplete: boolean; historyFrom: BusinessDate; privacyMode: boolean; hidePrivateToday: boolean;
};
export type MutationResult<T> = { ok: true; data: T } | { ok: false; message: string; code: "validation" | "conflict" | "storage" };
export type HabitLogInput = { habitId: string; date: BusinessDate; status: HabitLog["status"] | "clear"; completionCount: number; notes?: string; expectedRevision: number | null };
export type MetricLogInput = { metricId: string; date: BusinessDate; value: number | null; notes?: string; expectedRevision: number | null };
export type MetricIncrementInput = { metricId: string; date: BusinessDate; amount: number; operationId: string };
