import type { ScoreResult } from "@/features/tracking/domain";
function percent(fraction: number | null) { return fraction === null ? "—" : `${(fraction * 100).toFixed(1)}%`; }
export function ScorePanel({ result, title, privacyMode }: { result: ScoreResult; title: string; privacyMode: boolean }) {
  const empty = result.status === "future" ? "Future period" : result.status === "configuration" ? "Score configuration needs attention" : result.total === null ? "No scheduled targets" : null;
  return <section className="rounded-xl border bg-card p-5 sm:p-6" aria-label={`${title} score`}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-medium uppercase tracking-[0.14em] text-muted-foreground">{title} score</p><p className="mt-3 text-4xl font-semibold tabular-nums tracking-tight">{result.total === null ? "—" : result.total.toFixed(1)}{result.total !== null && <span className="ml-1 text-lg font-normal text-muted-foreground">/ 100</span>}</p><p className="mt-2 text-xs text-muted-foreground">{empty ?? (result.status === "in_progress" ? "In progress" : "Final")}</p></div><span className="rounded-full border px-3 py-1.5 text-xs text-muted-foreground">{result.start === result.end ? result.start : `${result.start} – ${result.end}`}</span></div>
    {result.coverage.expected > 0 && <p className="mt-4 text-xs text-muted-foreground">Logged opportunities: {result.coverage.recorded} of {result.coverage.expected}. Missing measurements differ from a logged zero.</p>}
    <details className="mt-5 border-t pt-4"><summary className="min-h-9 cursor-pointer text-sm font-medium">How this score is calculated</summary><div className="mt-3 space-y-4 text-sm"><p className="text-xs leading-5 text-muted-foreground">Only eligible sources contribute; their category weights are redistributed when a category has no eligible items. Scores cap achievement at 100%, while raw entries remain unchanged.</p>{result.categories.map((category)=><div key={category.category.id} className="border-l-2 border-primary/50 pl-3"><div className="flex justify-between gap-3 font-medium"><span>{category.category.name}</span><span>{percent(category.contribution)} · weight {category.weight}</span></div>{category.items.map((item)=><p key={item.item.id} className="mt-1 flex justify-between gap-3 text-xs text-muted-foreground"><span>{privacyMode && item.isPrivate ? "Private tracker" : item.name}</span><span>{percent(item.contribution)} · item weight {item.weight}</span></p>)}</div>)}{result.exclusions.length>0 && <div className="border-t pt-3"><p className="font-medium">Excluded inputs</p><ul className="mt-1 list-disc space-y-1 pl-5 text-xs text-muted-foreground">{result.exclusions.map((item,index)=><li key={`${item.itemId ?? "policy"}-${index}`}>{item.reason}</li>)}</ul></div>}</div></details>
  </section>;
}
