import { expect, test, type Page } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";

async function signIn(page: Page) {
  await page.goto("/login");
  await page.getByLabel("Email address").fill(process.env.E2E_AUTH_EMAIL!);
  await page.getByLabel("Password", { exact: true }).fill(process.env.E2E_AUTH_PASSWORD!);
  await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await expect(page).toHaveURL(/\/today$/);
}

test("weekly tasks reorder and carry only unfinished work", async ({ page }) => {
  test.setTimeout(120000);
  test.skip(!process.env.E2E_AUTH_EMAIL || !process.env.E2E_AUTH_PASSWORD, "Requires the dedicated confirmed test account.");
  const suffix = crypto.randomUUID().slice(0, 8);
  const first = `E2E planning ${suffix} first`;
  const done = `E2E planning ${suffix} done`;
  const isolatedDate = new Date(Date.UTC(2030, 0, 1));
  isolatedDate.setUTCDate(isolatedDate.getUTCDate() + parseInt(suffix.slice(0, 4), 16) % 300);
  await signIn(page);
  await page.goto(`/tasks?date=${isolatedDate.toISOString().slice(0, 10)}`);
  const addTask = () => page.locator("section").filter({ has: page.getByRole("heading", { name: "Add a task" }) });
  const sourceDate = await addTask().getByLabel("Plan for").inputValue();
  await addTask().getByRole("textbox", { name: "Task", exact: true }).fill(first);
  await addTask().getByLabel("Estimate (minutes)").fill("45");
  await addTask().getByLabel("Actual (minutes)").fill("10");
  await addTask().getByRole("button", { name: "Add task" }).click();
  await expect(page.getByRole("heading", { name: first })).toBeVisible({ timeout: 20000 });
  await page.reload();
  await addTask().getByRole("textbox", { name: "Task", exact: true }).fill(done);
  await addTask().getByLabel("Status").selectOption("completed");
  await addTask().getByRole("button", { name: "Add task" }).click();
  await expect(page.getByRole("heading", { name: done })).toBeVisible({ timeout: 20000 });
  await page.reload();
  await page.getByRole("button", { name: `Move ${done} up` }).click();
  await expect(page.locator("section[aria-labelledby='selected-tasks'] article h3").first()).toHaveText(done, { timeout: 20000 });
  const targetDate = await page.getByLabel("Later date").inputValue();
  await page.getByRole("button", { name: "Copy unfinished" }).click();
  await expect(page.getByText("1 unfinished task copied.")).toBeVisible({ timeout: 20000 });
  await page.goto(`/tasks?date=${targetDate}`);
  await expect(page.getByRole("heading", { name: first })).toBeVisible();
  await expect(page.getByRole("heading", { name: done })).toHaveCount(0);
  await expect(page.getByRole("article").filter({ has: page.getByRole("heading", { name: first }) })).toContainText("estimate 45 min");
  await expect(page.getByRole("article").filter({ has: page.getByRole("heading", { name: first }) })).not.toContainText("actual 10 min");
  await page.goto(`/tasks?date=${sourceDate}`);
  const nextDate = new Date(`${targetDate}T12:00:00Z`); nextDate.setUTCDate(nextDate.getUTCDate() + 1);
  await page.getByLabel("Later date").fill(nextDate.toISOString().slice(0, 10));
  await page.getByRole("button", { name: "Move unfinished" }).click();
  await expect(page.getByText("1 unfinished task moved.")).toBeVisible({ timeout: 20000 });
  await page.reload();
  await expect(page.getByRole("heading", { name: first })).toHaveCount(0);
  await expect(page.getByRole("heading", { name: done })).toBeVisible();
  expect((await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()).violations).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});

test("goals move between manual, milestone, and metric progress", async ({ page }) => {
  test.setTimeout(120000);
  test.skip(!process.env.E2E_AUTH_EMAIL || !process.env.E2E_AUTH_PASSWORD, "Requires the dedicated confirmed test account.");
  const title = `E2E planning ${crypto.randomUUID().slice(0, 8)} goal`;
  await signIn(page);
  await page.goto("/goals");
  await page.getByRole("textbox", { name: "Goal title" }).fill(title);
  await page.getByLabel("Manual progress (%)").fill("25");
  await page.getByRole("button", { name: "Create goal" }).click();
  await expect(page.getByRole("link").filter({ has: page.getByRole("heading", { name: title }) })).toBeVisible({ timeout: 20000 });
  await page.getByRole("link").filter({ has: page.getByRole("heading", { name: title }) }).click();
  await expect(page.getByText("25%", { exact: true })).toBeVisible();
  await page.getByLabel("Progress mode").selectOption("milestone");
  await page.getByRole("button", { name: "Save goal" }).click();
  await expect(page.getByText("Add a milestone to define progress.")).toBeVisible({ timeout: 20000 });
  await page.getByRole("textbox", { name: "New milestone" }).fill("E2E first step");
  await page.getByRole("button", { name: "Add milestone" }).click();
  await expect(page.getByRole("textbox", { name: "Milestone", exact: true })).toHaveValue("E2E first step", { timeout: 20000 });
  const milestoneForm = page.locator("form").filter({ has: page.locator('input[name="title"][value="E2E first step"]') });
  await milestoneForm.getByRole("checkbox", { name: "Complete" }).check();
  await milestoneForm.getByRole("button", { name: "Save milestone" }).click();
  await expect(page.getByText("100%", { exact: true })).toBeVisible({ timeout: 20000 });
  await page.getByLabel("Progress mode").selectOption("metric");
  const metric = page.getByLabel("Metric source");
  expect(await metric.locator("option").count()).toBeGreaterThan(1);
  await metric.selectOption({ index: 1 });
  await page.getByLabel("Baseline").fill("0");
  await page.getByLabel("Target value").fill("100");
  await page.getByRole("button", { name: "Save goal" }).click();
  await expect(page.getByText("metric progress", { exact: true })).toBeVisible({ timeout: 20000 });
  expect((await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()).violations).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});
