import Link from "next/link";
import { displayValue, trackerLabel } from "@/features/tracking/presentation";
import { ScorePanel } from "@/features/today/score-panel";
import type { InsightPoint, InsightReport, InsightsFilters, MetricSummary } from "./domain";
import { ScoreTrend } from "./score-trend";

function number(value: number | null, digits = 1) { return value === null ? "—" : value.toFixed(digits); }
function shade(value: number | null) {
  if (value === null) return "bg-secondary text-muted-foreground";
  if (value === 0) return "bg-destructive/20 text-foreground";
  if (value < 40) return "bg-warning/25 text-foreground";
  if (value < 70) return "bg-primary/20 text-foreground";
  if (value < 90) return "bg-primary/35 text-foreground";
  return "bg-success/25 text-foreground";
}

function Heatmap({ title, description, points }: { title: string; description: string; points: InsightPoint[] }) {
  const available = points.filter((point) => point.value !== null).length;
  return <section className="rounded-xl border bg-card p-5" aria-label={`${title} heatmap`}><div className="flex flex-wrap items-baseline justify-between gap-2"><h3 className="font-medium">{title}</h3><span className="text-xs tabular-nums text-muted-foreground">{available}/{points.length} scored dates</span></div><p className="mt-1 text-xs leading-5 text-muted-foreground">{description}</p>
    <ol aria-label={`${title} dates and values`} className="mt-4 grid grid-cols-7 gap-1.5">{points.map((point) => { const value = point.status === "configuration" ? "Score configuration needs attention" : point.value === null ? "No eligible target" : `${number(point.value)} percent`; const label = `${point.date}: ${value}; ${point.recorded} of ${point.expected} opportunities logged${point.status === "in_progress" ? "; in progress" : ""}`; return <li key={point.date} title={label} aria-label={label} className={`flex min-h-9 min-w-0 items-center justify-center rounded-md text-[10px] tabular-nums sm:text-xs ${shade(point.value)}`}>{point.value === null ? "—" : Math.round(point.value)}</li>; })}</ol>
    <p className="mt-3 text-xs text-muted-foreground">Numbers are percentages; 0 means an eligible result of zero, while — means no eligible result. Lighter cells do not imply missing records.</p>
  </section>;
}

function MetricCard({ metric, privacyMode }: { metric: MetricSummary; privacyMode: boolean }) {
  const label = privacyMode && metric.isPrivate ? "Private metric" : metric.label;
  return <article className="rounded-xl border bg-card p-4"><h3 className="font-medium">{label}</h3><p className="mt-2 text-2xl font-semibold tabular-nums">{displayValue(metric.latest, metric.unit)}</p><p className="mt-1 text-xs text-muted-foreground">Latest recorded value · {metric.recordedDays}/{metric.eligibleDays} eligible days recorded</p><p className="mt-3 text-sm text-muted-foreground">Recorded-day average: {displayValue(metric.average, metric.unit)}{metric.key === "steps" || metric.key === "water" || metric.key === "protein" ? ` · sum ${displayValue(metric.total, metric.unit)}` : ""}</p></article>;
}

export function InsightView({ report, filters, privacyMode }: { report: InsightReport; filters: InsightsFilters; privacyMode: boolean }) {
  const week = report.weekly;
  return <div className="space-y-9">
    <section aria-labelledby="score-overview"><h2 id="score-overview" className="text-xl font-medium">Score over time</h2><p className="mt-1 text-sm text-muted-foreground">Daily scores use each date’s effective policy. Weeks and quotas remain separate.</p><div className="mt-4 grid gap-4 sm:grid-cols-3">
      <article className="rounded-xl border bg-card p-5"><p className="text-xs uppercase tracking-wide text-muted-foreground">Average daily score</p><p className="mt-2 text-3xl font-semibold tabular-nums">{number(report.averageScore)}{report.averageScore !== null && <span className="text-base font-normal text-muted-foreground"> / 100</span>}</p><p className="mt-2 text-xs text-muted-foreground">{report.scoreDays}/{report.dates.length} dates had eligible score inputs.</p></article>
      <article className="rounded-xl border bg-card p-5"><p className="text-xs uppercase tracking-wide text-muted-foreground">Logging coverage</p><p className="mt-2 text-3xl font-semibold tabular-nums">{report.scoreCoverage.recorded}/{report.scoreCoverage.expected}</p><p className="mt-2 text-xs text-muted-foreground">Recorded / expected score opportunities. Missing differs from a logged zero.</p></article>
      <article className="rounded-xl border bg-card p-5"><p className="text-xs uppercase tracking-wide text-muted-foreground">Comparable week change</p><p className="mt-2 text-3xl font-semibold tabular-nums">{week.delta === null ? "—" : `${week.delta >= 0 ? "+" : ""}${number(week.delta)} pts`}</p><p className="mt-2 text-xs text-muted-foreground">{week.comparableDays} matching calendar days; {number(week.previous.total)} → {number(week.current.total)}.</p></article>
    </div><div className="mt-4 rounded-xl border bg-card p-5"><p className="mb-4 text-sm text-muted-foreground">Daily score trend, {filters.from}–{filters.to}. Gaps mean no scheduled target or a configuration issue; a real zero stays on the baseline.</p><ScoreTrend points={report.dailyScores} /></div>
    <details className="mt-4 rounded-xl border bg-card p-5"><summary className="min-h-9 cursor-pointer font-medium">How the compared weeks were scored</summary><p className="mt-2 text-sm text-muted-foreground">Current period through {week.current.evaluatedThrough}; previous through {week.previousThrough}. Each side uses its own historical policy and the same elapsed number of days. Open periods are in progress.</p><div className="mt-4 grid gap-4 lg:grid-cols-2"><ScorePanel title="Selected week" result={week.current} privacyMode={privacyMode} /><ScorePanel title="Previous matching days" result={week.previous} privacyMode={privacyMode} /></div></details>
    </section>
    <section aria-labelledby="heatmaps"><h2 id="heatmaps" className="text-xl font-medium">Consistency by date</h2><p className="mt-1 text-sm text-muted-foreground">Fitness and Career use the corresponding historical score category. Habit consistency uses only due daily opportunities; flexible quotas stay in weekly scores.</p><div className="mt-4 grid gap-4 lg:grid-cols-2"><Heatmap title="Overall" description="Full daily score across eligible categories." points={report.dailyScores} /><Heatmap title="Fitness" description="Fitness score category when it had eligible items." points={report.fitnessScores} /><Heatmap title="Career" description="Career score category when it had eligible items." points={report.careerScores} /><Heatmap title="Habits" description="Due daily habits within the selected tracker category." points={report.habitScores} /></div></section>
    <section aria-labelledby="category-breakdown"><h2 id="category-breakdown" className="text-xl font-medium">Score category breakdown</h2><p className="mt-1 text-sm text-muted-foreground">Average contribution on eligible dates. Score categories and tracker categories are separate settings.</p>{report.scoreCategories.length ? <div className="mt-4 grid gap-3 sm:grid-cols-2">{report.scoreCategories.map((category) => <article key={category.id} className="rounded-xl border bg-card p-4"><div className="flex justify-between gap-3 text-sm"><h3 className="font-medium">{category.name}</h3><span className="tabular-nums">{number(category.average)}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-primary" style={{ width: `${category.average}%` }} /></div><p className="mt-2 text-xs text-muted-foreground">{category.days} eligible dates</p></article>)}</div> : <p className="mt-4 rounded-xl border bg-card p-5 text-sm text-muted-foreground">No score categories had eligible inputs in this range.</p>}</section>
    <section aria-labelledby="fitness-summary"><h2 id="fitness-summary" className="text-xl font-medium">Fitness source records</h2><p className="mt-1 text-sm text-muted-foreground">Raw values stay uncapped. Averages divide by recorded days only; workout drafts are excluded.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{report.metrics.length ? report.metrics.map((metric) => <MetricCard key={metric.key} metric={metric} privacyMode={privacyMode} />) : <p className="rounded-xl border bg-card p-5 text-sm text-muted-foreground">No matching fitness metric definitions. <Link href="/fitness" className="text-primary underline">Set up Fitness</Link>.</p>}<article className="rounded-xl border bg-card p-4"><h3 className="font-medium">Completed workouts</h3><p className="mt-2 text-2xl font-semibold tabular-nums">{report.completedWorkouts ?? "—"}</p><p className="mt-1 text-xs text-muted-foreground">{report.completedWorkouts === null ? "Workouts have no tracker category; clear that filter to see the count." : "Shared completed sessions in the selected dates; drafts excluded."}</p></article></div></section>
    <section aria-labelledby="career-summary"><h2 id="career-summary" className="text-xl font-medium">Career source records</h2><p className="mt-1 text-sm text-muted-foreground">Saved study sessions are split across local-day boundaries for minutes and counted once on completion for sessions.</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><article className="rounded-xl border bg-card p-4"><h3 className="text-sm text-muted-foreground">Study time</h3><p className="mt-2 text-2xl font-semibold tabular-nums">{number(report.study.minutes, 0)} min</p></article><article className="rounded-xl border bg-card p-4"><h3 className="text-sm text-muted-foreground">Recorded days</h3><p className="mt-2 text-2xl font-semibold tabular-nums">{report.study.recordedDays}/{report.dates.length}</p></article><article className="rounded-xl border bg-card p-4"><h3 className="text-sm text-muted-foreground">Completed sessions</h3><p className="mt-2 text-2xl font-semibold tabular-nums">{report.study.sessionsCompleted}</p></article></div>{report.studyCategories.length ? <div className="mt-4 rounded-xl border bg-card p-5"><h3 className="font-medium">Time by study category</h3><ul className="mt-3 space-y-3">{report.studyCategories.map((category) => <li key={category.id} className="flex justify-between gap-3 text-sm"><span>{privacyMode ? "Private study category" : category.name}</span><span className="tabular-nums">{number(category.seconds / 60, 0)} min</span></li>)}</ul></div> : <p className="mt-4 text-sm text-muted-foreground">No matching study sessions in this period.</p>}</section>
    <section aria-labelledby="habit-rankings"><h2 id="habit-rankings" className="text-xl font-medium">Habits with scheduled opportunities</h2><p className="mt-1 text-sm text-muted-foreground">{report.rankedHabits} habits evaluated. Today’s still-pending opportunity is excluded from rankings; skipped dates contribute zero.</p><div className="mt-4 grid gap-4 lg:grid-cols-2"><div className="rounded-xl border bg-card p-5"><h3 className="font-medium">Strongest consistency</h3>{report.strongest.length ? <ol className="mt-3 space-y-3">{report.strongest.map((habit) => <li key={habit.id} className="flex justify-between gap-3 text-sm"><span>{trackerLabel(habit, { privacyMode })}</span><span className="shrink-0 tabular-nums">{number(habit.consistency * 100)}% · {habit.due} due</span></li>)}</ol> : <p className="mt-3 text-sm text-muted-foreground">No daily habit opportunities were due.</p>}</div><div className="rounded-xl border bg-card p-5"><h3 className="font-medium">Most missed opportunities</h3>{report.missed.length ? <ol className="mt-3 space-y-3">{report.missed.map((habit) => <li key={habit.id} className="flex justify-between gap-3 text-sm"><span>{trackerLabel(habit, { privacyMode })}</span><span className="shrink-0 tabular-nums">{habit.missed}/{habit.due} missed</span></li>)}</ol> : <p className="mt-3 text-sm text-muted-foreground">No missed or skipped daily opportunities in this range.</p>}</div></div></section>
    <p className="border-t pt-5 text-xs text-muted-foreground">Range coverage is {filters.from}–{filters.to}, inclusive. Scores retain historical schedules, targets, and policy versions. Category filtering narrows habit, metric, and study source summaries; policy scores remain whole-context. Challenge filtering limits dated eligibility while shared source records remain logged once.</p>
  </div>;
}
